swagger: "2.0"
info:
  description: "This API manage the information about a person."
  title: "Api persons"
host: "persons.gft"
basePath: "/v1"
tags:
- name: "person"
schemes:
- "http"
paths:
  /persons/:
    get:
      tags:
      - "person"
      summary: "Returns all people"
      description: ""
      operationId: "getPersons"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Person"
        204:
            description: "no content"
        500:
          description: "internal server error"
  /persons/{personId}:
    get:
      tags:
      - "person"
      summary: "Find person by ID"
      description: "Returns a single person"
      operationId: "getPersonById"
      produces:
      - "application/json"
      parameters:
      - name: "personId"
        in: "path"
        description: "ID of person"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Person"
        400:
          description: "invalid ID"
        404:
          description: "person not found"
        500:
          description: "internal server error"
definitions:
  Person:
    type: "object"
    required:
    - "id"
    - "name"
    - "last_name"
    - "phone"
    - "email"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        format: ""
      last_name:
        type: "string"
        format: ""
      phone:
        type: "string"
        format: ""
      email:
        type: "string"
        format: ""
      address:
        type: "string"
        format: ""